package br.com.nitrox.joaoDeBarro.business.model;

public interface JavaAttributeTypes {
	
	int JAVA_ATTRIBUTE_TYPE_INT = 1;
	int JAVA_ATTRIBUTE_TYPE_LONG = 2;
	int JAVA_ATTRIBUTE_TYPE_FLOAT = 3;
	int JAVA_ATTRIBUTE_TYPE_STRING = 4;
	int JAVA_ATTRIBUTE_TYPE_DATE = 5;
	int JAVA_ATTRIBUTE_TYPE_INTEGER_WRAPPER = 6;
	int JAVA_ATTRIBUTE_TYPE_FLOAT_WRAPPER = 7;
	int JAVA_ATTRIBUTE_TYPE_BOOLEAN_WRAPPER = 8;
	int JAVA_ATTRIBUTE_TYPE_BOOLEAN = 9;
	
}
