package br.com.nitrox.joaoDeBarro.common.persistence.dao.javaCode;

public interface JavaEntityConstants {
	
	int JAVA_ENTITY_SOLICITACAO = 1;
	int JAVA_ENTITY_DATA_STAGING_HPD_HELP_DESK = 2;
	int JAVA_ENTITY_DATA_STAGING_HPD_AUDIT_LOG_SYSTEM = 3;
	int JAVA_ENTITY_TIPO_SOLICITACAO = 4;
	int JAVA_ENTITY_PRODUTO_TI = 5;
	int JAVA_ENTITY_DATA_STAGING_NOTES_PEDIDO = 6;
	int JAVA_ENTITY_CSV_NOTES_PEDIDO = 7;
	int JAVA_ENTITY_COLABORADOR = 8;
	int JAVA_ENTITY_SISTEMA_TI = 9;
	int JAVA_ENTITY_DATA_STAGING_CONTAGEM_PROJETO_MELHORIA = 10;
	
	int[] JAVA_ENTITY_CODE_ARRAY = new int[] {
			JAVA_ENTITY_SOLICITACAO,
			JAVA_ENTITY_DATA_STAGING_HPD_HELP_DESK,
			JAVA_ENTITY_DATA_STAGING_HPD_AUDIT_LOG_SYSTEM,
			JAVA_ENTITY_TIPO_SOLICITACAO,
			JAVA_ENTITY_PRODUTO_TI,
			JAVA_ENTITY_DATA_STAGING_NOTES_PEDIDO,
			JAVA_ENTITY_CSV_NOTES_PEDIDO,
			JAVA_ENTITY_COLABORADOR,
			JAVA_ENTITY_SISTEMA_TI,
			JAVA_ENTITY_DATA_STAGING_CONTAGEM_PROJETO_MELHORIA
	};
	
	String JAVA_ENTITY_NAME_SOLICITACAO = "solicitacao";
	String JAVA_ENTITY_NAME_DATA_STAGING_HPD_HELP_DESK = "data_staging_hpd_help_desk";
	String JAVA_ENTITY_NAME_DATA_STAGING_HPD_AUDIT_LOG_SYSTEM = "data_staging_hpd_audit_log_system";
	String JAVA_ENTITY_NAME_TIPO_SOLICITACAO = "tipo_solicitacao";
	String JAVA_ENTITY_NAME_PRODUTO_TI = "produto_TI";
	String JAVA_ENTITY_NAME_DATA_STAGING_NOTES_PEDIDO = "data_staging_notes_pedido";
	String JAVA_ENTITY_NAME_CSV_NOTES_PEDIDO = "csv_notes_pedido";
	String JAVA_ENTITY_NAME_COLABORADOR = "colaborador";
	String JAVA_ENTITY_NAME_SISTEMA_TI = "sistema_TI";
	String JAVA_ENTITY_NAME_DATA_STAGING_CONTAGEM_PROJETO_MELHORIA = "data_staging_contagem_projeto_melhoria";
	
	String JAVA_TABLE_NAME_SOLICITACAO = "CAD_SOLIC_TI";
	String JAVA_TABLE_NAME_DATA_STAGING_HPD_HELP_DESK = "CAD_REMEDY_HPD_HELP_DESK";
	String JAVA_TABLE_NAME_DATA_STAGING_HPD_AUDIT_LOG_SYSTEM = "CAD_REMEDY_HPD_AUDIT_LOG_SYSTEM";
	String JAVA_TABLE_NAME_TIPO_SOLICITACAO = "CAD_TIP_SOLIC_TI";
	String JAVA_TABLE_NAME_PRODUTO = "Viw_GPS_Produto_TI";
	String JAVA_TABLE_NAME_DATA_STAGING_NOTES_PEDIDO = "CAD_NOTES_PEDIDO";
	String JAVA_TABLE_NAME_COLABORADOR = "Viw_GPS_Colaboradores_Bas";
	String JAVA_TABLE_NAME_SISTEMA_TI = "Viw_GPS_Sistema_TI_Bas";
	String JAVA_TABLE_NAME_DATA_STAGING_CONTAGEM_PROJETO_MELHORIA = "CAD_CONTGM_PROJ_MLHRIA";
	
}
