package br.com.nitrox.joaoDeBarro.common.persistence.dao.javaCode;

public interface JavaEntityConstants {
	
	int JAVA_ENTITY_SOLICITACAO = 1;
	int JAVA_ENTITY_DATA_STAGING_HPD_HELP_DESK = 2;
	int JAVA_ENTITY_DATA_STAGING_HPD_AUDIT_LOG_SYSTEM = 3;
	int JAVA_ENTITY_TIPO_SOLICITACAO = 4;
	int JAVA_ENTITY_PRODUTO = 5;
	
	int[] JAVA_ENTITY_CODE_ARRAY = new int[] {
			JAVA_ENTITY_SOLICITACAO,
			JAVA_ENTITY_DATA_STAGING_HPD_HELP_DESK,
			JAVA_ENTITY_DATA_STAGING_HPD_AUDIT_LOG_SYSTEM,
			JAVA_ENTITY_TIPO_SOLICITACAO,
			JAVA_ENTITY_PRODUTO
	};
	
	String JAVA_ENTITY_NAME_SOLICITACAO = "solicitacao";
	String JAVA_ENTITY_NAME_DATA_STAGING_HPD_HELP_DESK = "data_staging_hpd_help_desk";
	String JAVA_ENTITY_NAME_DATA_STAGING_HPD_AUDIT_LOG_SYSTEM = "data_staging_hpd_audit_log_system";
	String JAVA_ENTITY_NAME_TIPO_SOLICITACAO = "tipo_solicitacao";
	String JAVA_ENTITY_NAME_PRODUTO = "produto";
	
	String JAVA_TABLE_NAME_SOLICITACAO = "CAD_SOLIC_TI";
	String JAVA_TABLE_NAME_DATA_STAGING_HPD_HELP_DESK = "CAD_REMEDY_HPD_HELP_DESK";
	String JAVA_TABLE_NAME_DATA_STAGING_HPD_AUDIT_LOG_SYSTEM = "CAD_REMEDY_HPD_AUDIT_LOG_SYSTEM";
	String JAVA_TABLE_NAME_TIPO_SOLICITACAO = "CAD_TIP_SOLIC_TI";
	String JAVA_TABLE_NAME_PRODUTO = "CAD_PRDT_TI";
	
}
