package br.com.nitrox.joaoDeBarro.common.business.services.generators;

public interface JoaoDeBarroVelocityConstants {
	
	int TEMPLATE_TO_STRING_METHOD = 1;
	int TEMPLATE_CLASS_OPENING = 2;
	int TEMPLATE_ATTRIBUTE_DECLARATIONS = 3;
	
	int TEMPLATE_COMMON_SET_METHOD = 4;
	int TEMPLATE_FLOAT_WRAPPER_SET_METHOD = 5;
	int TEMPLATE_INTEGER_WRAPPER_SET_METHOD = 6;
	
	int TEMPLATE_COMMON_GET_METHOD = 7;
	int TEMPLATE_DATE_GET_METHOD = 8;
	
	int TEMPLATE_MAVEN_MODULE_CREATE_WORKSPACE_DIRECTORIES = 9;
	int TEMPLATE_MAVEN_MODULE_DELIVERY_TO_VERSION_CONTROL_DIR = 10;
	int TEMPLATE_MAVEN_MODULE_DELIVERY_TO_WORKSPACE = 11;
	int TEMPLATE_MAVEN_MODULE_UPDATE_FROM_VERSION_CONTROL_DIR = 12;
	int TEMPLATE_MAVEN_MODULE_UPDATE_FROM_WORKSPACE = 13;
	
	int TEMPLATE_SQL_SQLSERVER_INSERT_STOREDPROCEDURE = 14;
	
	int TEMPLATE_DAO_ANSISQL99_TRUNCATE_METHOD = 15;
	int TEMPLATE_DAO_ANSISQL99_CREATE_METHOD = 16;
	int TEMPLATE_DAO_ANSISQL99_UPDATE_METHOD = 17;
	int TEMPLATE_DAO_ANSISQL99_DELETE_METHOD = 18;
	int TEMPLATE_DAO_ANSISQL99_RETRIEVE_METHOD = 19;
	
	int TEMPLATE_ATTRIBUTE_CLONE = 20;
	
	int TEMPLATE_SQL_ANSISQL99_CREATE_TABLE = 21;
	
}
