package br.com.nitrox.joaoDeBarro.ambiente.infrastructure;

public interface Databases {
	
	int DATABASE_DEMANDAS_ACCESS_PRD = 101;
	int DATABASE_DEMANDAS_ACCESS_HOM = 102;
	int DATABASE_DEMANDAS_ACCESS_DSV = 103;
	
	int DATABASE_DEMANDAS_HSQLDB_PRD = 104;
	int DATABASE_DEMANDAS_HSQLDB_HOM = 105;
	int DATABASE_DEMANDAS_HSQLDB_DSV = 106;
	int DATABASE_DEMANDAS_HSQLDB_TST = 107;
	
	int DATABASE_SQL_SERVER_DSV = 108;
	int DATABASE_SQL_SERVER_HOM = 109;
	int DATABASE_SQL_SERVER_PRD = 110;
	
	int DATABASE_REGISTRO_DE_HORAS_ALDAN = 1;
	int DATABASE_REGISTRO_DE_HORAS_ALEXB = 2;
	int DATABASE_REGISTRO_DE_HORAS_AMATO = 3;
	int DATABASE_REGISTRO_DE_HORAS_ANIBO = 4;
	int DATABASE_REGISTRO_DE_HORAS_ANMEL = 5;
	int DATABASE_REGISTRO_DE_HORAS_APUPP = 6;
	int DATABASE_REGISTRO_DE_HORAS_ATRIN = 7;
	int DATABASE_REGISTRO_DE_HORAS_BFMIR = 8;
	int DATABASE_REGISTRO_DE_HORAS_CACAL = 9;
	int DATABASE_REGISTRO_DE_HORAS_CECAM = 10;
	int DATABASE_REGISTRO_DE_HORAS_CGANT = 11;
	int DATABASE_REGISTRO_DE_HORAS_CGIL = 12;
	int DATABASE_REGISTRO_DE_HORAS_DANVP = 13;
	int DATABASE_REGISTRO_DE_HORAS_EBITT = 14;
	int DATABASE_REGISTRO_DE_HORAS_EDUMN = 15;
	int DATABASE_REGISTRO_DE_HORAS_FABLO = 16;
	int DATABASE_REGISTRO_DE_HORAS_FCM = 17;
	int DATABASE_REGISTRO_DE_HORAS_FCNET = 18;
	int DATABASE_REGISTRO_DE_HORAS_FFIER = 19;
	int DATABASE_REGISTRO_DE_HORAS_FILTS = 20;
	int DATABASE_REGISTRO_DE_HORAS_FMGOM = 21;
	int DATABASE_REGISTRO_DE_HORAS_FPERE = 22;
	int DATABASE_REGISTRO_DE_HORAS_GDMS = 23;
	int DATABASE_REGISTRO_DE_HORAS_GGDSS = 24;
	int DATABASE_REGISTRO_DE_HORAS_GIELO = 25;
	int DATABASE_REGISTRO_DE_HORAS_GISEL = 26;
	int DATABASE_REGISTRO_DE_HORAS_GPES = 27;
	int DATABASE_REGISTRO_DE_HORAS_GSEG = 28;
	int DATABASE_REGISTRO_DE_HORAS_IVANM = 29;
	int DATABASE_REGISTRO_DE_HORAS_JAMS = 30;
	int DATABASE_REGISTRO_DE_HORAS_JOSEJ = 31;
	int DATABASE_REGISTRO_DE_HORAS_JOSEV = 32;
	int DATABASE_REGISTRO_DE_HORAS_KRLOS = 33;
	int DATABASE_REGISTRO_DE_HORAS_LEANR = 34;
	int DATABASE_REGISTRO_DE_HORAS_LEOMS = 35;
	int DATABASE_REGISTRO_DE_HORAS_LFILI = 36;
	int DATABASE_REGISTRO_DE_HORAS_LGCGO = 37;
	int DATABASE_REGISTRO_DE_HORAS_LIATP = 38;
	int DATABASE_REGISTRO_DE_HORAS_LJCP = 39;
	int DATABASE_REGISTRO_DE_HORAS_LSDMM = 40;
	int DATABASE_REGISTRO_DE_HORAS_LUCAM = 41;
	int DATABASE_REGISTRO_DE_HORAS_LUCOS = 42;
	int DATABASE_REGISTRO_DE_HORAS_LUIZZ = 43;
	int DATABASE_REGISTRO_DE_HORAS_MABHE = 44;
	int DATABASE_REGISTRO_DE_HORAS_MAJPC = 45;
	int DATABASE_REGISTRO_DE_HORAS_MANOT = 46;
	int DATABASE_REGISTRO_DE_HORAS_MAUR = 47;
	int DATABASE_REGISTRO_DE_HORAS_NRISI = 48;
	int DATABASE_REGISTRO_DE_HORAS_ONODA = 49;
	int DATABASE_REGISTRO_DE_HORAS_PPPPP = 50;
	int DATABASE_REGISTRO_DE_HORAS_RAB = 51;
	int DATABASE_REGISTRO_DE_HORAS_RAFBR = 52;
	int DATABASE_REGISTRO_DE_HORAS_RGAMA = 53;
	int DATABASE_REGISTRO_DE_HORAS_RICAB = 54;
	int DATABASE_REGISTRO_DE_HORAS_RLEMO = 55;
	int DATABASE_REGISTRO_DE_HORAS_RLMFX = 56;
	int DATABASE_REGISTRO_DE_HORAS_RPCAS = 57;
	int DATABASE_REGISTRO_DE_HORAS_SANTO = 58;
	int DATABASE_REGISTRO_DE_HORAS_SETTA = 59;
	int DATABASE_REGISTRO_DE_HORAS_SOMAF = 60;
	int DATABASE_REGISTRO_DE_HORAS_STUCK = 61;
	int DATABASE_REGISTRO_DE_HORAS_THORL = 62;
	int DATABASE_REGISTRO_DE_HORAS_VRODR = 63;
	int DATABASE_REGISTRO_DE_HORAS_WALDY = 64;
	int DATABASE_REGISTRO_DE_HORAS_XIMEN = 65;
	int DATABASE_REGISTRO_DE_HORAS_ZENON = 66;
	
	
	int[] REGISTRO_DE_HORAS_DATABASES = new int[] {
			DATABASE_REGISTRO_DE_HORAS_ALDAN,
			DATABASE_REGISTRO_DE_HORAS_ALEXB,
			DATABASE_REGISTRO_DE_HORAS_AMATO,
			DATABASE_REGISTRO_DE_HORAS_ANIBO,
			DATABASE_REGISTRO_DE_HORAS_ANMEL,
			DATABASE_REGISTRO_DE_HORAS_APUPP,
			DATABASE_REGISTRO_DE_HORAS_ATRIN,
			DATABASE_REGISTRO_DE_HORAS_BFMIR,
			DATABASE_REGISTRO_DE_HORAS_CACAL,
			DATABASE_REGISTRO_DE_HORAS_CECAM,
			DATABASE_REGISTRO_DE_HORAS_CGANT,
			DATABASE_REGISTRO_DE_HORAS_CGIL,
			DATABASE_REGISTRO_DE_HORAS_DANVP,
			DATABASE_REGISTRO_DE_HORAS_EBITT,
			DATABASE_REGISTRO_DE_HORAS_EDUMN,
			DATABASE_REGISTRO_DE_HORAS_FABLO,
			DATABASE_REGISTRO_DE_HORAS_FCM,
			DATABASE_REGISTRO_DE_HORAS_FCNET,
			DATABASE_REGISTRO_DE_HORAS_FFIER,
			DATABASE_REGISTRO_DE_HORAS_FILTS,
			DATABASE_REGISTRO_DE_HORAS_FMGOM,
			DATABASE_REGISTRO_DE_HORAS_FPERE,
			DATABASE_REGISTRO_DE_HORAS_GDMS,
			DATABASE_REGISTRO_DE_HORAS_GGDSS,
			DATABASE_REGISTRO_DE_HORAS_GIELO,
			DATABASE_REGISTRO_DE_HORAS_GISEL,
			DATABASE_REGISTRO_DE_HORAS_GPES,
			DATABASE_REGISTRO_DE_HORAS_GSEG,
			DATABASE_REGISTRO_DE_HORAS_IVANM,
			DATABASE_REGISTRO_DE_HORAS_JAMS,
			DATABASE_REGISTRO_DE_HORAS_JOSEJ,
			DATABASE_REGISTRO_DE_HORAS_JOSEV,
			DATABASE_REGISTRO_DE_HORAS_KRLOS,
			DATABASE_REGISTRO_DE_HORAS_LEANR,
			DATABASE_REGISTRO_DE_HORAS_LEOMS,
			DATABASE_REGISTRO_DE_HORAS_LFILI,
			DATABASE_REGISTRO_DE_HORAS_LGCGO,
			DATABASE_REGISTRO_DE_HORAS_LIATP,
			DATABASE_REGISTRO_DE_HORAS_LJCP,
			DATABASE_REGISTRO_DE_HORAS_LSDMM,
			DATABASE_REGISTRO_DE_HORAS_LUCAM,
			DATABASE_REGISTRO_DE_HORAS_LUCOS,
			DATABASE_REGISTRO_DE_HORAS_LUIZZ,
			DATABASE_REGISTRO_DE_HORAS_MABHE,
			DATABASE_REGISTRO_DE_HORAS_MAJPC,
			DATABASE_REGISTRO_DE_HORAS_MANOT,
			DATABASE_REGISTRO_DE_HORAS_MAUR,
			DATABASE_REGISTRO_DE_HORAS_NRISI,
			DATABASE_REGISTRO_DE_HORAS_ONODA,
			DATABASE_REGISTRO_DE_HORAS_PPPPP,
			DATABASE_REGISTRO_DE_HORAS_RAB,
			DATABASE_REGISTRO_DE_HORAS_RAFBR,
			DATABASE_REGISTRO_DE_HORAS_RGAMA,
			DATABASE_REGISTRO_DE_HORAS_RICAB,
			DATABASE_REGISTRO_DE_HORAS_RLEMO,
			DATABASE_REGISTRO_DE_HORAS_RLMFX,
			DATABASE_REGISTRO_DE_HORAS_RPCAS,
			DATABASE_REGISTRO_DE_HORAS_SANTO,
			DATABASE_REGISTRO_DE_HORAS_SETTA,
			DATABASE_REGISTRO_DE_HORAS_SOMAF,
			DATABASE_REGISTRO_DE_HORAS_STUCK,
			DATABASE_REGISTRO_DE_HORAS_THORL,
			DATABASE_REGISTRO_DE_HORAS_VRODR,
			DATABASE_REGISTRO_DE_HORAS_WALDY,
			DATABASE_REGISTRO_DE_HORAS_XIMEN,
			DATABASE_REGISTRO_DE_HORAS_ZENON
	};
	
}
