package br.com.nitrox.joaoDeBarro.ambiente.infrastructure;

public interface SgbdTypes {
	
	int SGBD_TYPE_ACCESS = 1;
	int SGBD_TYPE_MSSQLSERVER = 2;
	int SGBD_TYPE_HSQLDB = 3;
	int SGBD_TYPE_ORACLE = 4;
	int SGBD_TYPE_ANSISQL99 = 5;
	
	String SGBD_TYPE_NAME_ACCESS = "ACCESS";
	String SGBD_TYPE_NAME_MSSQLSERVER = "MSSQL_SERVER";
	String SGBD_TYPE_NAME_HSQLDB = "HSQLDB";
	String SGBD_TYPE_NAME_ORACLE = "ORACLE";
	String SGBD_TYPE_NAME_ANSISQL99 = "ANSI_SQL_99";
	
	int[] SGBD_TYPE_CODES = new int[] {
		SGBD_TYPE_ACCESS,
		SGBD_TYPE_MSSQLSERVER,
		SGBD_TYPE_HSQLDB,
		SGBD_TYPE_ORACLE,
		SGBD_TYPE_ANSISQL99
	};
	
	String[] SGBD_TYPE_NAMES = new String[] {
		SGBD_TYPE_NAME_ACCESS,
		SGBD_TYPE_NAME_MSSQLSERVER,
		SGBD_TYPE_NAME_HSQLDB,
		SGBD_TYPE_NAME_ORACLE,
		SGBD_TYPE_NAME_ANSISQL99
	};
	
}
